# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydemo
  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
        - name: hello-app
          # replace PROJECT_ID as per gcloud project
          image: gcr.io/PROJECT_ID/my-demo-gke
          args: [ "--scheme", "http", "--host", "0.0.0.0", "--port", "8080" ]
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8080
              protocol: "TCP"
              name: hello-app